### PR TITLE
Improved ci

### PR DESCRIPTION
**Pull request by AdrieanKhisbe**
add node 8 to the travis build and setup coverage with codecov

### CODE REVIEW

**Comment by davglass** [comment]
Thanks!

**Comment by AdrieanKhisbe** [comment]
@davglass I started working on a slight es6 refresh (const/let) and improved signature.
Are you interested in? :)

**Comment by AdrieanKhisbe** [comment]
here is a preview: https://github.com/davglass/prettysize/compare/master...AdrieanKhisbe:es6-refresh?expand=1

**Comment by davglass** [comment]
Sure, this looks good. Only thing I would add is the `--fix` to the `eslint` call to auto fix issues it finds..

**Comment by AdrieanKhisbe** [comment]
I can add a `lint:fix` task, though `npm run lint -- --fix` would works.
Do you want me to set it by default?

**Comment by AdrieanKhisbe** [comment]
@davglass I opened the PR:https://github.com/davglass/prettysize/pull/6

**Pull request merged**
